version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing components..."
      - yarn install
  build:
    commands:
      - echo "$GIT_CHECKOUT_COMMAND"
      - eval $GIT_CHECKOUT_COMMAND
      - echo "Building JS & CSS..."
      - echo "Environment $ENV"
      - yarn run ng build --configuration=$ENV

artifacts:
  name: code_files
  base-directory: dist/awconnect
  files:
    - "**/*"
