name: 'stale branch'
description: 'Add a git tag to the current workflow commit'
author: 'basivireddy'
inputs:
  repo_name:
    description: repo
runs:
  using: "composite"
  steps:
    - name: Run a one-line script
      run: echo Hello, world! ; echo "${{ github.event.inputs.repo_name }}"
      shell: bash

    - run: bash ./.github/workflows/actions/stale/s-b.sh "${{ github.event.inputs.repo_name }}"
      shell: bash
      
