name: 'Git Tag Action'
description: 'Add a git tag to the current workflow commit'
author: 'kiran'
runs:
  using: "composite"
  steps:
    - name: Run a one-line script
      run: echo Hello, world!
      shell: bash
    
    - run: bash ./.github/workflows/actions/helm-version-auto-increment/autoincrement.sh
      shell: bash
